# Intro to numpy

We start by importing numpy

In [1]:
import numpy as np

We can take a python list and turn that into an array object 
array([item1, item2, item3])


In [2]:
my_array_list = [1,2,3]

In [5]:
array = np.array(my_array_list)

In [7]:
array

array([1, 2, 3])

this is a one dimensionsal array, a two dimensional array would be a list of lists

In [8]:
my_matt = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matt)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

An example of a two dimensional array. It contains two sets of brackets indicating it as a two dimensional array.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arrange creates an array similar to pythons range function.
arrange takes three arguements: the start, the end, the step size.

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

np.zeros: creates an array of zeros. this method takes one argument. a number will return a single vector with columns corresponding to the argument.

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

if you pass a tuple to the zeros method, you get a two dimensional array with rows relating to the first number in the tuple, and colums relating to the second.

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [26]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

linspace returns a one dimensional vector of evenly spaced points between the first two arguements

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

eye creates an identity matrix. this takes in one argument and returns a sqare matrix with a size relating to the given argument. see: https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:properties-of-matrix-multiplication/a/intro-to-identity-matrices

In [28]:
np.random.rand(5)

array([0.05923776, 0.39769213, 0.04299611, 0.85398825, 0.18335413])

random.rand returns an array of random numbers between 0 and 1, the argument defines the length of the array.

In [30]:
np.random.rand(5,5)

array([[0.89256295, 0.7060684 , 0.97251414, 0.39911786, 0.11900257],
       [0.73762459, 0.37159475, 0.96614915, 0.91183436, 0.84896283],
       [0.70826096, 0.06610862, 0.64427392, 0.94259938, 0.21529445],
       [0.86129994, 0.62134462, 0.5870646 , 0.29443589, 0.33240043],
       [0.70189161, 0.91522283, 0.64524779, 0.79442548, 0.85027397]])

When two arguments are passed in, random.rand reutrns a two dimensional array, the first argument defines the columns, the second defines the rows.

In [31]:
np.random.randn(2)

array([0.81114367, 0.82520353])

random.randn returns an array of random numbers from a standard normal distribution.

see: https://www.khanacademy.org/math/statistics-probability/modeling-distributions-of-data


In [33]:
np.random.randn(2,4)

array([[-0.49663879,  0.95141934, -0.65089684, -0.45748612],
       [-0.38167327, -0.14874905,  0.12598608,  1.36677087]])

In [38]:
np.random.randint(1,100, 10)

array([23, 47, 60, 92, 13, 89, 40, 71, 89, 52])

random.randint returns a random number between the two passed arguments. the third argument describes the ammount of results you want.

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
randomarr = np.random.randint(0,50,10)

In [45]:
randomarr

array([ 3, 29, 22, 48,  3, 13, 10, 31,  0, 30])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

the {array}.reshape method lets you reshape a defined array. the arguements retate to the new dimensions you want.

check that your arguments relate to the total number of elements you want to change in the array. (e.g. 5*5 = 25)

In [49]:
randomarr.max()

48

In [50]:
randomarr.min()

0

In [52]:
randomarr.argmax()

3

In [53]:
randomarr.argmin()


8

In [55]:
arr = arr.reshape(5,5)

In [56]:
arr.shape

(5, 5)

In [1]:
arr.dtype

NameError: name 'arr' is not defined

# Indexing and Selection

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:4]

array([1, 2, 3])

In [8]:
arr[5: ]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

numpy arrays have a method of changing elements called 'broadcasting'

In [12]:
arr = np.arange(0,11)


In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[0:6] = 100

In [16]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Remember that if you slice an array and broadcast it, you also change the original array

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr 

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 100

In [22]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

the slice_of_arr in this case acts more like a view rather than a new array

to copy an original array, you specify it.

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [25]:
arr_copy[:] = 99

In [26]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [27]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [17]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d[0]

array([ 5, 10, 15])

returns the row of a matrix

In [16]:
arr_2d[0][0]

5

returns a sngleelement in the matrix, the first brackets for the row, the second for the column

In [21]:
arr_2d[1,1]

25

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

you can use index slicing to grab chuncks of the index

In [26]:
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

In [28]:
bigger_arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [29]:
bigger_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
bigger_arr[1: 3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [47]:
arr = np.arange(1,11)

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr_bool = arr > 5

In [53]:
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

when you pass a conditional to an array, a boolean array is returned

In [52]:
arr[arr_bool]

array([ 6,  7,  8,  9, 10])

you can pass a boolean array as grab chuncks that meet the condition.

In [54]:
arr[arr<3]

array([1, 2])

this is the more common short hand version.

In [55]:
arr_2d = np.arange(50).reshape(5,10)

In [56]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[2:,7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

# NumPy Operations

In [63]:
arr = np.arange(0,11)

In [64]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [67]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [68]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [69]:
arr/arr

C:\Users\William\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

if you need to perform operations that result in errors (for example division by zero) numpy can continue to execute code and will instead issue a warning.

In [70]:
1/arr

C:\Users\William\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [71]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [74]:
arr.max()

10

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

you can perform arithmetic operations on arrays using numpy. more operations can be found at --->  https://docs.scipy.org/doc/numpy/reference/ufuncs.html